// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: proto/xray/xray.proto

package xraypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_UNKNOWN Direction = 0
	Direction_DIRECTION_IN      Direction = 1
	Direction_DIRECTION_OUT     Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNKNOWN",
		1: "DIRECTION_IN",
		2: "DIRECTION_OUT",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNKNOWN": 0,
		"DIRECTION_IN":      1,
		"DIRECTION_OUT":     2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_xray_xray_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_proto_xray_xray_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{0}
}

type CloseReason int32

const (
	CloseReason_CLOSE_REASON_UNKNOWN     CloseReason = 0
	CloseReason_CLOSE_REASON_CLOSE       CloseReason = 1
	CloseReason_CLOSE_REASON_RESET       CloseReason = 2
	CloseReason_CLOSE_REASON_CONN_CLOSED CloseReason = 3
)

// Enum value maps for CloseReason.
var (
	CloseReason_name = map[int32]string{
		0: "CLOSE_REASON_UNKNOWN",
		1: "CLOSE_REASON_CLOSE",
		2: "CLOSE_REASON_RESET",
		3: "CLOSE_REASON_CONN_CLOSED",
	}
	CloseReason_value = map[string]int32{
		"CLOSE_REASON_UNKNOWN":     0,
		"CLOSE_REASON_CLOSE":       1,
		"CLOSE_REASON_RESET":       2,
		"CLOSE_REASON_CONN_CLOSED": 3,
	}
)

func (x CloseReason) Enum() *CloseReason {
	p := new(CloseReason)
	*p = x
	return p
}

func (x CloseReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloseReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_xray_xray_proto_enumTypes[1].Descriptor()
}

func (CloseReason) Type() protoreflect.EnumType {
	return &file_proto_xray_xray_proto_enumTypes[1]
}

func (x CloseReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloseReason.Descriptor instead.
func (CloseReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{1}
}

type Envelope struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Seq          uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ObservedAtNs int64                  `protobuf:"varint,2,opt,name=observed_at_ns,json=observedAtNs,proto3" json:"observed_at_ns,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_SnapshotStart
	//	*Envelope_SnapshotEnd
	//	*Envelope_StringDef
	//	*Envelope_PeerUpsert
	//	*Envelope_ConnectionUpsert
	//	*Envelope_ConnectionClosed
	//	*Envelope_StreamUpsert
	//	*Envelope_StreamClosed
	//	*Envelope_StreamChunk
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_xray_xray_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xray_xray_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetObservedAtNs() int64 {
	if x != nil {
		return x.ObservedAtNs
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSnapshotStart() *SnapshotStart {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SnapshotStart); ok {
			return x.SnapshotStart
		}
	}
	return nil
}

func (x *Envelope) GetSnapshotEnd() *SnapshotEnd {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SnapshotEnd); ok {
			return x.SnapshotEnd
		}
	}
	return nil
}

func (x *Envelope) GetStringDef() *StringDef {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StringDef); ok {
			return x.StringDef
		}
	}
	return nil
}

func (x *Envelope) GetPeerUpsert() *PeerUpsert {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PeerUpsert); ok {
			return x.PeerUpsert
		}
	}
	return nil
}

func (x *Envelope) GetConnectionUpsert() *ConnectionUpsert {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ConnectionUpsert); ok {
			return x.ConnectionUpsert
		}
	}
	return nil
}

func (x *Envelope) GetConnectionClosed() *ConnectionClosed {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ConnectionClosed); ok {
			return x.ConnectionClosed
		}
	}
	return nil
}

func (x *Envelope) GetStreamUpsert() *StreamUpsert {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StreamUpsert); ok {
			return x.StreamUpsert
		}
	}
	return nil
}

func (x *Envelope) GetStreamClosed() *StreamClosed {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StreamClosed); ok {
			return x.StreamClosed
		}
	}
	return nil
}

func (x *Envelope) GetStreamChunk() *StreamChunk {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_StreamChunk); ok {
			return x.StreamChunk
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_SnapshotStart struct {
	SnapshotStart *SnapshotStart `protobuf:"bytes,11,opt,name=snapshot_start,json=snapshotStart,proto3,oneof"`
}

type Envelope_SnapshotEnd struct {
	SnapshotEnd *SnapshotEnd `protobuf:"bytes,12,opt,name=snapshot_end,json=snapshotEnd,proto3,oneof"`
}

type Envelope_StringDef struct {
	StringDef *StringDef `protobuf:"bytes,20,opt,name=string_def,json=stringDef,proto3,oneof"`
}

type Envelope_PeerUpsert struct {
	PeerUpsert *PeerUpsert `protobuf:"bytes,21,opt,name=peer_upsert,json=peerUpsert,proto3,oneof"`
}

type Envelope_ConnectionUpsert struct {
	ConnectionUpsert *ConnectionUpsert `protobuf:"bytes,22,opt,name=connection_upsert,json=connectionUpsert,proto3,oneof"`
}

type Envelope_ConnectionClosed struct {
	ConnectionClosed *ConnectionClosed `protobuf:"bytes,23,opt,name=connection_closed,json=connectionClosed,proto3,oneof"`
}

type Envelope_StreamUpsert struct {
	StreamUpsert *StreamUpsert `protobuf:"bytes,24,opt,name=stream_upsert,json=streamUpsert,proto3,oneof"`
}

type Envelope_StreamClosed struct {
	StreamClosed *StreamClosed `protobuf:"bytes,25,opt,name=stream_closed,json=streamClosed,proto3,oneof"`
}

type Envelope_StreamChunk struct {
	StreamChunk *StreamChunk `protobuf:"bytes,26,opt,name=stream_chunk,json=streamChunk,proto3,oneof"`
}

func (*Envelope_SnapshotStart) isEnvelope_Payload() {}

func (*Envelope_SnapshotEnd) isEnvelope_Payload() {}

func (*Envelope_StringDef) isEnvelope_Payload() {}

func (*Envelope_PeerUpsert) isEnvelope_Payload() {}

func (*Envelope_ConnectionUpsert) isEnvelope_Payload() {}

func (*Envelope_ConnectionClosed) isEnvelope_Payload() {}

func (*Envelope_StreamUpsert) isEnvelope_Payload() {}

func (*Envelope_StreamClosed) isEnvelope_Payload() {}

func (*Envelope_StreamChunk) isEnvelope_Payload() {}

type ClientHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	PeerId          []byte                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`                   // libp2p peer ID of the instrumented node
	ClientName      string                 `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`       // e.g. "prysm/v5.2.0", "lighthouse/v5.3.0"
	BootId          []byte                 `protobuf:"bytes,4,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`                   // changes each process restart
	StartedAtNs     int64                  `protobuf:"varint,5,opt,name=started_at_ns,json=startedAtNs,proto3" json:"started_at_ns,omitempty"` // probe process start time
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_proto_xray_xray_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xray_xray_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{1}
}

func (x *ClientHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ClientHello) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *ClientHello) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ClientHello) GetBootId() []byte {
	if x != nil {
		return x.BootId
	}
	return nil
}

func (x *ClientHello) GetStartedAtNs() int64 {
	if x != nil {
		return x.StartedAtNs
	}
	return 0
}

type ServerHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SourceId        string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`                // backend-assigned, stable across reconnects
	LastAckedSeq    uint64                 `protobuf:"varint,3,opt,name=last_acked_seq,json=lastAckedSeq,proto3" json:"last_acked_seq,omitempty"` // highest seq the server has applied for this source; 0 = fresh attach
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_proto_xray_xray_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xray_xray_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{2}
}

func (x *ServerHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ServerHello) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ServerHello) GetLastAckedSeq() uint64 {
	if x != nil {
		return x.LastAckedSeq
	}
	return 0
}

type SnapshotStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotStart) Reset() {
	*x = SnapshotStart{}
	mi := &file_proto_xray_xray_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotStart) ProtoMessage() {}

func (x *SnapshotStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xray_xray_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotStart.ProtoReflect.Descriptor instead.
func (*SnapshotStart) Descriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{3}
}

type SnapshotEnd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshot state includes events through this sequence. Zero is a legacy snapshot.
	LastIncludedSeq uint64 `protobuf:"varint,1,opt,name=last_included_seq,json=lastIncludedSeq,proto3" json:"last_included_seq,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotEnd) Reset() {
	*x = SnapshotEnd{}
	mi := &file_proto_xray_xray_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEnd) ProtoMessage() {}

func (x *SnapshotEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xray_xray_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEnd.ProtoReflect.Descriptor instead.
func (*SnapshotEnd) Descriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotEnd) GetLastIncludedSeq() uint64 {
	if x != nil {
		return x.LastIncludedSeq
	}
	return 0
}

type StringDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringDef) Reset() {
	*x = StringDef{}
	mi := &file_proto_xray_xray_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringDef) ProtoMessage() {}

func (x *StringDef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xray_xray_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringDef.ProtoReflect.Descriptor instead.
func (*StringDef) Descriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{5}
}

func (x *StringDef) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StringDef) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PeerUpsert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerAlias     uint64                 `protobuf:"varint,1,opt,name=peer_alias,json=peerAlias,proto3" json:"peer_alias,omitempty"`
	PeerId        []byte                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerUpsert) Reset() {
	*x = PeerUpsert{}
	mi := &file_proto_xray_xray_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerUpsert) ProtoMessage() {}

func (x *PeerUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xray_xray_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerUpsert.ProtoReflect.Descriptor instead.
func (*PeerUpsert) Descriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{6}
}

func (x *PeerUpsert) GetPeerAlias() uint64 {
	if x != nil {
		return x.PeerAlias
	}
	return 0
}

func (x *PeerUpsert) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

type ConnectionUpsert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnAlias     uint64                 `protobuf:"varint,1,opt,name=conn_alias,json=connAlias,proto3" json:"conn_alias,omitempty"`
	PeerAlias     uint64                 `protobuf:"varint,2,opt,name=peer_alias,json=peerAlias,proto3" json:"peer_alias,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	LocalAddr     string                 `protobuf:"bytes,4,opt,name=local_addr,json=localAddr,proto3" json:"local_addr,omitempty"`
	Direction     Direction              `protobuf:"varint,5,opt,name=direction,proto3,enum=xray.v1.Direction" json:"direction,omitempty"`
	TransportId   uint32                 `protobuf:"varint,6,opt,name=transport_id,json=transportId,proto3" json:"transport_id,omitempty"`
	SecurityId    uint32                 `protobuf:"varint,7,opt,name=security_id,json=securityId,proto3" json:"security_id,omitempty"`
	MuxerId       uint32                 `protobuf:"varint,8,opt,name=muxer_id,json=muxerId,proto3" json:"muxer_id,omitempty"`
	OpenedAtNs    int64                  `protobuf:"varint,9,opt,name=opened_at_ns,json=openedAtNs,proto3" json:"opened_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionUpsert) Reset() {
	*x = ConnectionUpsert{}
	mi := &file_proto_xray_xray_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionUpsert) ProtoMessage() {}

func (x *ConnectionUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xray_xray_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionUpsert.ProtoReflect.Descriptor instead.
func (*ConnectionUpsert) Descriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectionUpsert) GetConnAlias() uint64 {
	if x != nil {
		return x.ConnAlias
	}
	return 0
}

func (x *ConnectionUpsert) GetPeerAlias() uint64 {
	if x != nil {
		return x.PeerAlias
	}
	return 0
}

func (x *ConnectionUpsert) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *ConnectionUpsert) GetLocalAddr() string {
	if x != nil {
		return x.LocalAddr
	}
	return ""
}

func (x *ConnectionUpsert) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNKNOWN
}

func (x *ConnectionUpsert) GetTransportId() uint32 {
	if x != nil {
		return x.TransportId
	}
	return 0
}

func (x *ConnectionUpsert) GetSecurityId() uint32 {
	if x != nil {
		return x.SecurityId
	}
	return 0
}

func (x *ConnectionUpsert) GetMuxerId() uint32 {
	if x != nil {
		return x.MuxerId
	}
	return 0
}

func (x *ConnectionUpsert) GetOpenedAtNs() int64 {
	if x != nil {
		return x.OpenedAtNs
	}
	return 0
}

type ConnectionClosed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnAlias     uint64                 `protobuf:"varint,1,opt,name=conn_alias,json=connAlias,proto3" json:"conn_alias,omitempty"`
	ClosedAtNs    int64                  `protobuf:"varint,2,opt,name=closed_at_ns,json=closedAtNs,proto3" json:"closed_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionClosed) Reset() {
	*x = ConnectionClosed{}
	mi := &file_proto_xray_xray_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionClosed) ProtoMessage() {}

func (x *ConnectionClosed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xray_xray_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionClosed.ProtoReflect.Descriptor instead.
func (*ConnectionClosed) Descriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectionClosed) GetConnAlias() uint64 {
	if x != nil {
		return x.ConnAlias
	}
	return 0
}

func (x *ConnectionClosed) GetClosedAtNs() int64 {
	if x != nil {
		return x.ClosedAtNs
	}
	return 0
}

type StreamUpsert struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	StreamAlias uint64                 `protobuf:"varint,1,opt,name=stream_alias,json=streamAlias,proto3" json:"stream_alias,omitempty"`
	ConnAlias   uint64                 `protobuf:"varint,2,opt,name=conn_alias,json=connAlias,proto3" json:"conn_alias,omitempty"`
	Direction   Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=xray.v1.Direction" json:"direction,omitempty"`
	ProtocolId  uint32                 `protobuf:"varint,4,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	OpenedAtNs  int64                  `protobuf:"varint,5,opt,name=opened_at_ns,json=openedAtNs,proto3" json:"opened_at_ns,omitempty"`
	// The stream's framing prefix was not captured. Count raw bytes until it closes.
	CaptureStartedMidstream bool `protobuf:"varint,6,opt,name=capture_started_midstream,json=captureStartedMidstream,proto3" json:"capture_started_midstream,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StreamUpsert) Reset() {
	*x = StreamUpsert{}
	mi := &file_proto_xray_xray_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUpsert) ProtoMessage() {}

func (x *StreamUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xray_xray_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUpsert.ProtoReflect.Descriptor instead.
func (*StreamUpsert) Descriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{9}
}

func (x *StreamUpsert) GetStreamAlias() uint64 {
	if x != nil {
		return x.StreamAlias
	}
	return 0
}

func (x *StreamUpsert) GetConnAlias() uint64 {
	if x != nil {
		return x.ConnAlias
	}
	return 0
}

func (x *StreamUpsert) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNKNOWN
}

func (x *StreamUpsert) GetProtocolId() uint32 {
	if x != nil {
		return x.ProtocolId
	}
	return 0
}

func (x *StreamUpsert) GetOpenedAtNs() int64 {
	if x != nil {
		return x.OpenedAtNs
	}
	return 0
}

func (x *StreamUpsert) GetCaptureStartedMidstream() bool {
	if x != nil {
		return x.CaptureStartedMidstream
	}
	return false
}

type StreamClosed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamAlias   uint64                 `protobuf:"varint,1,opt,name=stream_alias,json=streamAlias,proto3" json:"stream_alias,omitempty"`
	ClosedAtNs    int64                  `protobuf:"varint,2,opt,name=closed_at_ns,json=closedAtNs,proto3" json:"closed_at_ns,omitempty"`
	Reason        CloseReason            `protobuf:"varint,3,opt,name=reason,proto3,enum=xray.v1.CloseReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamClosed) Reset() {
	*x = StreamClosed{}
	mi := &file_proto_xray_xray_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamClosed) ProtoMessage() {}

func (x *StreamClosed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xray_xray_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamClosed.ProtoReflect.Descriptor instead.
func (*StreamClosed) Descriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{10}
}

func (x *StreamClosed) GetStreamAlias() uint64 {
	if x != nil {
		return x.StreamAlias
	}
	return 0
}

func (x *StreamClosed) GetClosedAtNs() int64 {
	if x != nil {
		return x.ClosedAtNs
	}
	return 0
}

func (x *StreamClosed) GetReason() CloseReason {
	if x != nil {
		return x.Reason
	}
	return CloseReason_CLOSE_REASON_UNKNOWN
}

type StreamChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamAlias   uint64                 `protobuf:"varint,1,opt,name=stream_alias,json=streamAlias,proto3" json:"stream_alias,omitempty"`
	Direction     Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=xray.v1.Direction" json:"direction,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunk) Reset() {
	*x = StreamChunk{}
	mi := &file_proto_xray_xray_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunk) ProtoMessage() {}

func (x *StreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_xray_xray_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunk.ProtoReflect.Descriptor instead.
func (*StreamChunk) Descriptor() ([]byte, []int) {
	return file_proto_xray_xray_proto_rawDescGZIP(), []int{11}
}

func (x *StreamChunk) GetStreamAlias() uint64 {
	if x != nil {
		return x.StreamAlias
	}
	return 0
}

func (x *StreamChunk) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNKNOWN
}

func (x *StreamChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_xray_xray_proto protoreflect.FileDescriptor

const file_proto_xray_xray_proto_rawDesc = "" +
	"\n" +
	"\x15proto/xray/xray.proto\x12\axray.v1\"\x87\x05\n" +
	"\bEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12$\n" +
	"\x0eobserved_at_ns\x18\x02 \x01(\x03R\fobservedAtNs\x12?\n" +
	"\x0esnapshot_start\x18\v \x01(\v2\x16.xray.v1.SnapshotStartH\x00R\rsnapshotStart\x129\n" +
	"\fsnapshot_end\x18\f \x01(\v2\x14.xray.v1.SnapshotEndH\x00R\vsnapshotEnd\x123\n" +
	"\n" +
	"string_def\x18\x14 \x01(\v2\x12.xray.v1.StringDefH\x00R\tstringDef\x126\n" +
	"\vpeer_upsert\x18\x15 \x01(\v2\x13.xray.v1.PeerUpsertH\x00R\n" +
	"peerUpsert\x12H\n" +
	"\x11connection_upsert\x18\x16 \x01(\v2\x19.xray.v1.ConnectionUpsertH\x00R\x10connectionUpsert\x12H\n" +
	"\x11connection_closed\x18\x17 \x01(\v2\x19.xray.v1.ConnectionClosedH\x00R\x10connectionClosed\x12<\n" +
	"\rstream_upsert\x18\x18 \x01(\v2\x15.xray.v1.StreamUpsertH\x00R\fstreamUpsert\x12<\n" +
	"\rstream_closed\x18\x19 \x01(\v2\x15.xray.v1.StreamClosedH\x00R\fstreamClosed\x129\n" +
	"\fstream_chunk\x18\x1a \x01(\v2\x14.xray.v1.StreamChunkH\x00R\vstreamChunkB\t\n" +
	"\apayloadJ\x04\b\n" +
	"\x10\v\"\xaf\x01\n" +
	"\vClientHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\fR\x06peerId\x12\x1f\n" +
	"\vclient_name\x18\x03 \x01(\tR\n" +
	"clientName\x12\x17\n" +
	"\aboot_id\x18\x04 \x01(\fR\x06bootId\x12\"\n" +
	"\rstarted_at_ns\x18\x05 \x01(\x03R\vstartedAtNs\"{\n" +
	"\vServerHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12$\n" +
	"\x0elast_acked_seq\x18\x03 \x01(\x04R\flastAckedSeq\"\x0f\n" +
	"\rSnapshotStart\"9\n" +
	"\vSnapshotEnd\x12*\n" +
	"\x11last_included_seq\x18\x01 \x01(\x04R\x0flastIncludedSeq\"1\n" +
	"\tStringDef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"D\n" +
	"\n" +
	"PeerUpsert\x12\x1d\n" +
	"\n" +
	"peer_alias\x18\x01 \x01(\x04R\tpeerAlias\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\fR\x06peerId\"\xc3\x02\n" +
	"\x10ConnectionUpsert\x12\x1d\n" +
	"\n" +
	"conn_alias\x18\x01 \x01(\x04R\tconnAlias\x12\x1d\n" +
	"\n" +
	"peer_alias\x18\x02 \x01(\x04R\tpeerAlias\x12\x1f\n" +
	"\vremote_addr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x04 \x01(\tR\tlocalAddr\x120\n" +
	"\tdirection\x18\x05 \x01(\x0e2\x12.xray.v1.DirectionR\tdirection\x12!\n" +
	"\ftransport_id\x18\x06 \x01(\rR\vtransportId\x12\x1f\n" +
	"\vsecurity_id\x18\a \x01(\rR\n" +
	"securityId\x12\x19\n" +
	"\bmuxer_id\x18\b \x01(\rR\amuxerId\x12 \n" +
	"\fopened_at_ns\x18\t \x01(\x03R\n" +
	"openedAtNs\"S\n" +
	"\x10ConnectionClosed\x12\x1d\n" +
	"\n" +
	"conn_alias\x18\x01 \x01(\x04R\tconnAlias\x12 \n" +
	"\fclosed_at_ns\x18\x02 \x01(\x03R\n" +
	"closedAtNs\"\x81\x02\n" +
	"\fStreamUpsert\x12!\n" +
	"\fstream_alias\x18\x01 \x01(\x04R\vstreamAlias\x12\x1d\n" +
	"\n" +
	"conn_alias\x18\x02 \x01(\x04R\tconnAlias\x120\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x12.xray.v1.DirectionR\tdirection\x12\x1f\n" +
	"\vprotocol_id\x18\x04 \x01(\rR\n" +
	"protocolId\x12 \n" +
	"\fopened_at_ns\x18\x05 \x01(\x03R\n" +
	"openedAtNs\x12:\n" +
	"\x19capture_started_midstream\x18\x06 \x01(\bR\x17captureStartedMidstream\"\x81\x01\n" +
	"\fStreamClosed\x12!\n" +
	"\fstream_alias\x18\x01 \x01(\x04R\vstreamAlias\x12 \n" +
	"\fclosed_at_ns\x18\x02 \x01(\x03R\n" +
	"closedAtNs\x12,\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x14.xray.v1.CloseReasonR\x06reason\"v\n" +
	"\vStreamChunk\x12!\n" +
	"\fstream_alias\x18\x01 \x01(\x04R\vstreamAlias\x120\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x12.xray.v1.DirectionR\tdirection\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data*G\n" +
	"\tDirection\x12\x15\n" +
	"\x11DIRECTION_UNKNOWN\x10\x00\x12\x10\n" +
	"\fDIRECTION_IN\x10\x01\x12\x11\n" +
	"\rDIRECTION_OUT\x10\x02*u\n" +
	"\vCloseReason\x12\x18\n" +
	"\x14CLOSE_REASON_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12CLOSE_REASON_CLOSE\x10\x01\x12\x16\n" +
	"\x12CLOSE_REASON_RESET\x10\x02\x12\x1c\n" +
	"\x18CLOSE_REASON_CONN_CLOSED\x10\x03B*Z(github.com/ethp2p/xray/proto/xray;xraypbb\x06proto3"

var (
	file_proto_xray_xray_proto_rawDescOnce sync.Once
	file_proto_xray_xray_proto_rawDescData []byte
)

func file_proto_xray_xray_proto_rawDescGZIP() []byte {
	file_proto_xray_xray_proto_rawDescOnce.Do(func() {
		file_proto_xray_xray_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_xray_xray_proto_rawDesc), len(file_proto_xray_xray_proto_rawDesc)))
	})
	return file_proto_xray_xray_proto_rawDescData
}

var file_proto_xray_xray_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_xray_xray_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_xray_xray_proto_goTypes = []any{
	(Direction)(0),           // 0: xray.v1.Direction
	(CloseReason)(0),         // 1: xray.v1.CloseReason
	(*Envelope)(nil),         // 2: xray.v1.Envelope
	(*ClientHello)(nil),      // 3: xray.v1.ClientHello
	(*ServerHello)(nil),      // 4: xray.v1.ServerHello
	(*SnapshotStart)(nil),    // 5: xray.v1.SnapshotStart
	(*SnapshotEnd)(nil),      // 6: xray.v1.SnapshotEnd
	(*StringDef)(nil),        // 7: xray.v1.StringDef
	(*PeerUpsert)(nil),       // 8: xray.v1.PeerUpsert
	(*ConnectionUpsert)(nil), // 9: xray.v1.ConnectionUpsert
	(*ConnectionClosed)(nil), // 10: xray.v1.ConnectionClosed
	(*StreamUpsert)(nil),     // 11: xray.v1.StreamUpsert
	(*StreamClosed)(nil),     // 12: xray.v1.StreamClosed
	(*StreamChunk)(nil),      // 13: xray.v1.StreamChunk
}
var file_proto_xray_xray_proto_depIdxs = []int32{
	5,  // 0: xray.v1.Envelope.snapshot_start:type_name -> xray.v1.SnapshotStart
	6,  // 1: xray.v1.Envelope.snapshot_end:type_name -> xray.v1.SnapshotEnd
	7,  // 2: xray.v1.Envelope.string_def:type_name -> xray.v1.StringDef
	8,  // 3: xray.v1.Envelope.peer_upsert:type_name -> xray.v1.PeerUpsert
	9,  // 4: xray.v1.Envelope.connection_upsert:type_name -> xray.v1.ConnectionUpsert
	10, // 5: xray.v1.Envelope.connection_closed:type_name -> xray.v1.ConnectionClosed
	11, // 6: xray.v1.Envelope.stream_upsert:type_name -> xray.v1.StreamUpsert
	12, // 7: xray.v1.Envelope.stream_closed:type_name -> xray.v1.StreamClosed
	13, // 8: xray.v1.Envelope.stream_chunk:type_name -> xray.v1.StreamChunk
	0,  // 9: xray.v1.ConnectionUpsert.direction:type_name -> xray.v1.Direction
	0,  // 10: xray.v1.StreamUpsert.direction:type_name -> xray.v1.Direction
	1,  // 11: xray.v1.StreamClosed.reason:type_name -> xray.v1.CloseReason
	0,  // 12: xray.v1.StreamChunk.direction:type_name -> xray.v1.Direction
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_xray_xray_proto_init() }
func file_proto_xray_xray_proto_init() {
	if File_proto_xray_xray_proto != nil {
		return
	}
	file_proto_xray_xray_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_SnapshotStart)(nil),
		(*Envelope_SnapshotEnd)(nil),
		(*Envelope_StringDef)(nil),
		(*Envelope_PeerUpsert)(nil),
		(*Envelope_ConnectionUpsert)(nil),
		(*Envelope_ConnectionClosed)(nil),
		(*Envelope_StreamUpsert)(nil),
		(*Envelope_StreamClosed)(nil),
		(*Envelope_StreamChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_xray_xray_proto_rawDesc), len(file_proto_xray_xray_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_xray_xray_proto_goTypes,
		DependencyIndexes: file_proto_xray_xray_proto_depIdxs,
		EnumInfos:         file_proto_xray_xray_proto_enumTypes,
		MessageInfos:      file_proto_xray_xray_proto_msgTypes,
	}.Build()
	File_proto_xray_xray_proto = out.File
	file_proto_xray_xray_proto_goTypes = nil
	file_proto_xray_xray_proto_depIdxs = nil
}
